### PR TITLE
Remove CCO position

### PR DESCRIPTION
**Pull request by devksingh4**

### CODE REVIEW

**Comment by devksingh4** [comment]
I approve

**Review by simoneangelov — APPROVED** [review]
I approve

**Review by EthanHaque — APPROVED** [review]
I approve

**Review by Cowen22 — COMMENTED** [review]
Aye.

**Review by Cowen22 — APPROVED** [review]

**Review by dasarchan — APPROVED** [review]
bleh bleh bleh github

**Comment by devksingh4** [comment]
Quorum Established with 5 members
Merging as approved by board

**Pull request merged**
