### PR TITLE
Add purchasing guidelines

### PR DESCRIPTION
**Pull request by devksingh4**

### CODE REVIEW

**Comment by EthanHaque** [comment]
I vote yes

**Comment by Cowen22** [comment]
I vote yes

**Review by EthanHaque — APPROVED** [review]

**Review by Cowen22 — APPROVED** [review]

**Review by simoneangelov — APPROVED** [review]
I also approve

**Comment by devksingh4** [comment]
I vote yes

**Review by Chairless-maybe — COMMENTED** [review]
I vote yes

**Pull request merged**
